CREATE TABLE IF NOT EXISTS `invalidate_events`
(
    `id`         BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `seq`        BIGINT UNSIGNED NULL,
    `data`       TEXT            NOT NULL,
    `created_at` TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `invalidate_offsets`
(
    `server_name` VARCHAR(100)    NOT NULL PRIMARY KEY,
    `last_seq`    BIGINT UNSIGNED NOT NULL,
    `created_at`  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);