name: cacheinv
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql
        ports:
        - 3306:3306
        env:
          MYSQL_DATABASE: cache_inv
          MYSQL_ROOT_PASSWORD: 1
          MYSQL_PORT: 3306
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: 1
      redis1:
        image: redis
        ports:
        - 6379:6379
      redis2:
        image: redis
        ports:
        - 6380:6379
      memcached1:
        image: memcached
        ports:
        - 11211:11211
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Install Tools
      run: make install-tools
    - name: Lint
      run: make lint
    - name: Test
      run: make test
    - name: Test Race
      run: make test-race
    - name: Coverage
      run: make coverage
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.6
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
